---

- name: Create _build directory
  file:
    path: "{{ dockerfile_dest }}/{{ template_dest }}"
    state: directory

- name: Render supervisor configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ dockerfile_dest }}/{{ template_dest }}/{{ item }}"
  with_items:
    - "supervisor.conf"
    - "supervisor_task.conf"

- name: Render Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ dockerfile_dest }}/{{ dockerfile_name }}"

- name: Add mount_helper in Dockerfile
  replace:
      path: "{{ dockerfile_dest }}/{{ dockerfile_name }}"
<<<<<<< HEAD
      regexp: '#mount_helper'
      replace: 'mount_helper'
=======
      regexp: '^#mount_helper'
      replace: '\1'
>>>>>>> 75fcb8ac053f655e61d2e236051d31cd51886554
